force-app/main/default/objects/CaseFTTHComponent__c/CaseFTTHComponent__c.object-meta.xml
<CustomObject>
    <label>Case FTTH Component</label>
    <nameField>
        <label>FTTH Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case FTTH Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case FTTH Components</relationshipLabel>
    <relationshipName>Case_FTTH_Components</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Circle</label>
    <referenceTo>Circles__c</referenceTo>
    <relationshipLabel>Case FTTH Components</relationshipLabel>
    <relationshipName>Case_FTTH_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/ComponentId__c.field-meta.xml
<CustomField>
    <fullName>ComponentId__c</fullName>
    <label>Component Id</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/ComponentType__c.field-meta.xml
<CustomField>
    <fullName>ComponentType__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GPON</fullName>
            </value>
            <value>
                <fullName>FAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/FDCLocation__c.field-meta.xml
<CustomField>
    <fullName>FDCLocation__c</fullName>
    <label>FDC Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/FieldEngineer__c.field-meta.xml
<CustomField>
    <fullName>FieldEngineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_FTTH_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/InstallationAddress__c.field-meta.xml
<CustomField>
    <fullName>InstallationAddress__c</fullName>
    <label>Installation Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/IsMobilityConnected__c.field-meta.xml
<CustomField>
    <fullName>IsMobilityConnected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the GPON/FAT is connected to a Mobility Tower in which case the impact will be huge in case of an issue with this GPON/FAT</description>
    <inlineHelpText>This field indicates if the GPON/FAT is connected to a Mobility Tower in which case the impact will be huge in case of an issue with this GPON/FAT</inlineHelpText>
    <label>Is Mobility Connected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/IsReported__c.field-meta.xml
<CustomField>
    <fullName>IsReported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsReported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCaseComponentAfterInsertTrigger.cls
@isTest
public class TestCaseComponentAfterInsertTrigger {
    @isTest static void testmethod1(){
        Case testcase=new Case(
            Line_of_Business__c = 'FTTH',
            GPON_Id__c = '0O2-Z1/3/10',
            IsExcelRecord__c = true,
            Origin='Telegram',
            //FieldEngineerUser__c='005C7000000IXRZIA4',
            Status='New',
            HoldReason__c='Access issue',
            FTTHCaseType__c='PON'
        );
       	insert testcase;
        Case myCase = [SELECT Id FROM Case LIMIT 1];
        CaseFTTHComponent__c CFC = new CaseFTTHComponent__c();
                CFC.ComponentType__c='GPON';
                CFC.ComponentId__c = '0O2-Z1/3/10';
                CFC.Case__c= myCase.Id;
                CFC.InstallationAddress__c = '-Flat No AL6/7/9 Room No 9,Omkar Apartment,Airoli Sector 5,Navi Mumbai,,Th,ane,Maharashtra,400708,,Thane,Maharashtra,400708';
                CFC.FDCLocation__c = 'FDC ON-TERRACE-OMKAR APARTMENT BUILDING NO 07';
                CFC.IsMobilityConnected__c = false;
               // CFC.FieldEngineer__c = '00571000002DNIbAAO';
                //CFC.Circle__c = 'a39710000007ohdAAA';
                CFC.IsReported__c=true;
                CFC.Latitude__c= '19.148418';
                CFC.Longitude__c= '72.9941';
                insert CFC;
    }
     @isTest static void testmethod2(){
        Case testcase=new Case(
            Line_of_Business__c = 'FTTH',
            GPON_Id__c = '0O2-Z1/3/10',
            IsExcelRecord__c = true,
            Origin='Telegram',
            //FieldEngineerUser__c='005C7000000IXRZIA4',
            Status='New',
            HoldReason__c='Access issue'
        );
       	insert testcase;
        Case myCase = [SELECT Id FROM Case LIMIT 1];
        CaseFTTHComponent__c CFC = new CaseFTTHComponent__c();
                CFC.ComponentType__c='FAT';
                CFC.ComponentId__c = '0O2-Z1/3/10';
                CFC.Case__c= myCase.Id;
                CFC.InstallationAddress__c = '-Flat No AL6/7/9 Room No 9,Omkar Apartment,Airoli Sector 5,Navi Mumbai,,Th,ane,Maharashtra,400708,,Thane,Maharashtra,400708';
                CFC.FDCLocation__c = 'FDC ON-TERRACE-OMKAR APARTMENT BUILDING NO 07';
                CFC.IsMobilityConnected__c = false;
                //CFC.FieldEngineer__c = '00571000002DNIbAAO';
                //CFC.Circle__c = 'a39710000007ohdAAA';
                CFC.IsReported__c=true;
                CFC.Latitude__c= '19.148418';
                CFC.Longitude__c= '72.9941';
                insert CFC;
    }
    @isTest static void testmethod3(){
        Case testcase=new Case(
            Line_of_Business__c = 'FTTH',
            GPON_Id__c = '0O2-Z1/3/10',
            IsExcelRecord__c = true,
            Origin='Telegram',
            //FieldEngineerUser__c='005C7000000IXRZIA4',
            Status='New',
            HoldReason__c='Access issue',
            FTTHCaseType__c='PON',
            FTTHInformation__c = 'Test method 3'
        );
       	insert testcase;
        Case myCase = [SELECT Id FROM Case LIMIT 1];
        CaseFTTHComponent__c CFC = new CaseFTTHComponent__c();
                CFC.ComponentType__c='GPON';
                CFC.ComponentId__c = '0O2-Z1/3/10';
                CFC.Case__c= myCase.Id;
                CFC.InstallationAddress__c = '-Flat No AL6/7/9 Room No 9,Omkar Apartment,Airoli Sector 5,Navi Mumbai,,Th,ane,Maharashtra,400708,,Thane,Maharashtra,400708';
                CFC.FDCLocation__c = 'FDC ON-TERRACE-OMKAR APARTMENT BUILDING NO 07';
                CFC.IsMobilityConnected__c = false;
               // CFC.FieldEngineer__c = '00571000002DNIbAAO';
               // CFC.Circle__c = 'a39710000007ohdAAA';
                CFC.IsReported__c=true;
                CFC.Latitude__c= '19.148418';
                CFC.Longitude__c= '72.9941';
                insert CFC;
    }
    @isTest static void testmethod4(){
        Case testcase=new Case(
            Line_of_Business__c = 'FTTH',
            GPON_Id__c = '0O2-Z1/3/10',
            IsExcelRecord__c = true,
            Origin='Telegram',
            //FieldEngineerUser__c='005C7000000IXRZIA4',
            Status='New',
            HoldReason__c='Access issue',
            FTTHInformation__c = 'Test Method 4'
        );
       	insert testcase;
        Case myCase = [SELECT Id FROM Case LIMIT 1];
        CaseFTTHComponent__c CFC = new CaseFTTHComponent__c();
                CFC.ComponentType__c='FAT';
                CFC.ComponentId__c = '0O2-Z1/3/10';
                CFC.Case__c= myCase.Id;
                CFC.InstallationAddress__c = '-Flat No AL6/7/9 Room No 9,Omkar Apartment,Airoli Sector 5,Navi Mumbai,,Th,ane,Maharashtra,400708,,Thane,Maharashtra,400708';
                CFC.FDCLocation__c = 'FDC ON-TERRACE-OMKAR APARTMENT BUILDING NO 07';
                CFC.IsMobilityConnected__c = false;
              //  CFC.FieldEngineer__c = '00571000002DNIbAAO';
                //CFC.Circle__c = 'a39710000007ohdAAA';
                CFC.IsReported__c=true;
                CFC.Latitude__c= '19.148418';
                CFC.Longitude__c= '72.9941';
                insert CFC;
    }
}