force-app/main/default/objects/CaseFTTHComponent__c/CaseFTTHComponent__c.object-meta.xml
<CustomObject>
    <label>Case FTTH Component</label>
    <nameField>
        <label>FTTH Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case FTTH Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case FTTH Components</relationshipLabel>
    <relationshipName>Case_FTTH_Components</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Circle</label>
    <referenceTo>Circles__c</referenceTo>
    <relationshipLabel>Case FTTH Components</relationshipLabel>
    <relationshipName>Case_FTTH_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/ComponentId__c.field-meta.xml
<CustomField>
    <fullName>ComponentId__c</fullName>
    <label>Component Id</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/ComponentType__c.field-meta.xml
<CustomField>
    <fullName>ComponentType__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GPON</fullName>
            </value>
            <value>
                <fullName>FAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/FDCLocation__c.field-meta.xml
<CustomField>
    <fullName>FDCLocation__c</fullName>
    <label>FDC Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/FieldEngineer__c.field-meta.xml
<CustomField>
    <fullName>FieldEngineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_FTTH_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/InstallationAddress__c.field-meta.xml
<CustomField>
    <fullName>InstallationAddress__c</fullName>
    <label>Installation Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/IsMobilityConnected__c.field-meta.xml
<CustomField>
    <fullName>IsMobilityConnected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the GPON/FAT is connected to a Mobility Tower in which case the impact will be huge in case of an issue with this GPON/FAT</description>
    <inlineHelpText>This field indicates if the GPON/FAT is connected to a Mobility Tower in which case the impact will be huge in case of an issue with this GPON/FAT</inlineHelpText>
    <label>Is Mobility Connected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/IsReported__c.field-meta.xml
<CustomField>
    <fullName>IsReported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsReported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Holds the floor/wing of the apartment/building (especially for FAT)</description>
    <inlineHelpText>Holds the floor/wing of the apartment/building (especially for FAT)</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseFTTHComponent__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circles__c/Circles__c.object-meta.xml
<CustomObject>
    <label>Circles</label>
    <nameField>
        <label>Telecom Circle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circuit__c/Circuit__c.object-meta.xml
<CustomObject>
    <description>This objects holds the Master data for OHFC and UG Circuits for Service Cloud Ticketing</description>
    <label>Circuit</label>
    <nameField>
        <label>Circuit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circuits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circuit__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Circle</label>
    <referenceTo>Circles__c</referenceTo>
    <relationshipLabel>Circuits</relationshipLabel>
    <relationshipName>Circuits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circuit__c/fields/CircuitId__c.field-meta.xml
<CustomField>
    <fullName>CircuitId__c</fullName>
    <description>Circuit Id of OHFC and UG</description>
    <externalId>true</externalId>
    <inlineHelpText>Circuit Id of OHFC and UG</inlineHelpText>
    <label>Circuit Id</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Circuit__c/fields/CustomerCircuitId__c.field-meta.xml
<CustomField>
    <fullName>CustomerCircuitId__c</fullName>
    <label>Customer Circuit Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Circuit__c/fields/FieldEngineer__c.field-meta.xml
<CustomField>
    <fullName>FieldEngineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Circuits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circuit__c/fields/RouteName__c.field-meta.xml
<CustomField>
    <fullName>RouteName__c</fullName>
    <label>Route Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAT__c/FAT__c.object-meta.xml
<CustomObject>
    <description>Fiber Access Terminal (FAT) is the secondary splitter, the outputs from which the homes are directly connected</description>
    <label>FAT</label>
    <nameField>
        <label>FAT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FATs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FAT__c/fields/FATFullAddress__c.field-meta.xml
<CustomField>
    <fullName>FATFullAddress__c</fullName>
    <description>Installation Address of the FAT Box (Fiber Access Terminal)</description>
    <inlineHelpText>Installation Address of the FAT Box (Fiber Access Terminal)</inlineHelpText>
    <label>FAT Full Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FAT__c/fields/FATLocation__c.field-meta.xml
<CustomField>
    <fullName>FATLocation__c</fullName>
    <description>Holds the wing/floor of the apartment/building</description>
    <inlineHelpText>Holds the wing/floor of the apartment/building</inlineHelpText>
    <label>FAT Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAT__c/fields/FATNumber__c.field-meta.xml
<CustomField>
    <fullName>FATNumber__c</fullName>
    <externalId>true</externalId>
    <label>FAT Number</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FAT__c/fields/FDCLocation__c.field-meta.xml
<CustomField>
    <fullName>FDCLocation__c</fullName>
    <label>FDCLocation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FAT__c/fields/GPON__c.field-meta.xml
<CustomField>
    <fullName>GPON__c</fullName>
    <label>GPON</label>
    <referenceTo>GPON__c</referenceTo>
    <relationshipName>FATBoxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FAT__c/fields/GPONId__c.field-meta.xml
<CustomField>
    <fullName>GPONId__c</fullName>
    <label>GPON Id</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAT__c/fields/IsMobilityConnected__c.field-meta.xml
<CustomField>
    <fullName>IsMobilityConnected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the FAT (Fiber Access Terminal) is connected to a Mobility Tower in which case the impact will be huge in case of an issue with this FAT</description>
    <inlineHelpText>This field indicates if the FAT i(Fiber Access Terminal) s connected to a Mobility Tower in which case the impact will be huge in case of an issue with this FAT</inlineHelpText>
    <label>Is Mobility Connected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GPON__c/GPON__c.object-meta.xml
<CustomObject>
    <label>GPON</label>
    <nameField>
        <label>GPON Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPONs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPON__c/fields/Circles__c.field-meta.xml
<CustomField>
    <fullName>Circles__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Circles</label>
    <referenceTo>Circles__c</referenceTo>
    <relationshipLabel>GPONs</relationshipLabel>
    <relationshipName>GPONs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPON__c/fields/FDCLocation__c.field-meta.xml
<CustomField>
    <fullName>FDCLocation__c</fullName>
    <label>FDC Location</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GPON__c/fields/FieldEngineer__c.field-meta.xml
<CustomField>
    <fullName>FieldEngineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field Engineer who is responsible for maintenance/issue fix of this GPON</description>
    <inlineHelpText>Field Engineer who is responsible for maintenance/issue fix of this GPON</inlineHelpText>
    <label>Field Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GPONs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPON__c/fields/GPONId__c.field-meta.xml
<CustomField>
    <fullName>GPONId__c</fullName>
    <externalId>true</externalId>
    <label>GPON Id</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GPON__c/fields/InstallationAddress__c.field-meta.xml
<CustomField>
    <fullName>InstallationAddress__c</fullName>
    <description>Installation Address of the GPON (Gigabit Passive Optical Network)</description>
    <inlineHelpText>Installation Address of the GPON (Gigabit Passive Optical Network)</inlineHelpText>
    <label>Installation Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPON__c/fields/IsMobilityConnected__c.field-meta.xml
<CustomField>
    <fullName>IsMobilityConnected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the GPON is connected to a Mobility Tower in which case the impact will be huge in case of an issue with this GPON</description>
    <inlineHelpText>This field indicates if the GPON is connected to a Mobility Tower in which case the impact will be huge in case of an issue with this GPON</inlineHelpText>
    <label>Is Mobility Connected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GPON__c/fields/Primary_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPONs</relationshipLabel>
    <relationshipName>GPONs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPON__c/fields/RSU__c.field-meta.xml
<CustomField>
    <fullName>RSU__c</fullName>
    <label>RSU</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceCloudUtil.cls
public class ServiceCloudUtil {
    //public static boolean firstRun = true; //for Case after update trigger that fires twice - to check by flag
    public static String getCircuitId(String emailDescription)
    {
        String circuitId = '',incidentId='',siteId='';
        if(String.isBlank(emailDescription)) return circuitId;
        String[] arr = emailDescription.split('\n'); 
        System.debug('SC array :' + arr.size());
            for(Integer i=0;i<arr.size();i++){
                String lcase = arr[i].substringBefore(':').toLowerCase();
                List<String> cids=new List<String>();
                System.debug('array'+arr[i]);
                if(lcase.contains('impacted')){
                    String ImpactedLine = arr[i].substringAfter(':');
                    System.debug('ImpactedLine'+ImpactedLine);
                    if(ImpactedLine.contains('CircuitID')){
                    	circuitId=ImpactedLine.substringAfter('CircuitID-').substringBefore('\n').trim();
                    	System.debug('Circuit Id-' + circuitId);
                    }
                    if(!ImpactedLine.contains('CircuitID') && !ImpactedLine.contains('SiteID')){
                        circuitId=arr[i].substringAfter(':').substringBefore('\n').trim();
                        System.debug('Circuit Id' + circuitId);
                        break;
                    }
                    break;
                }
                else if(lcase.contains('circuit id') || lcase.contains('circuitid'))
                {
                    circuitId=arr[i].substringAfter(':').substringBefore('\n').trim();
                    System.debug('Circuit Id' + circuitId);
                    break;
                }
        	}
        return circuitId;   
    }
    public static String getCircuitId2(String emailDescription)
    {
        String circuitId = '',incidentId='',siteId='';
        if(String.isBlank(emailDescription)) return circuitId;
        String[] arr = emailDescription.split('\n'); 
        System.debug('SC array :' + arr.size());
            for(Integer i=0;i<arr.size();i++){
                String lcase = arr[i].substringBefore(':').toLowerCase();
                List<String> cids=new List<String>();
                System.debug('array'+arr[i]);
                if(lcase.contains('impacted')){
                    String ImpactedLine = arr[i].substringAfter(':');
                    System.debug('ImpactedLine'+ImpactedLine);
                    
                    if(ImpactedLine.contains('SiteID')){
                        siteId=ImpactedLine.substringAfter('SiteID-').substringBefore('_CircuitID').trim();
                        System.debug('SiteId -'+siteId);
                    }
                    break;
                }
        	}
        return siteId;   
    }
    public static String getIncidentId(String emailDescription)
    {
        String incidentId = '';
        if(String.isBlank(emailDescription)) return incidentId;
        String[] arr = emailDescription.split('\n'); 
            for(Integer i=0;i<arr.size();i++){
                String lcase = arr[i].substringBefore(':').toLowerCase();
                System.debug('array'+arr[i]);
                if(lcase.contains('incident id') || lcase.contains('incidentid')){
                     incidentId=arr[i].substringAfter(':').substringBefore('\n').trim();
                     System.debug('Incident Id' + incidentId);
                    break;
                }
                
            }
        System.debug('Incident id is :'+incidentId);
        return incidentId;   
    }
    
    public static String getActualIncidentTime(String emailDescription)
    {
        String incidentTime = '';
        if(String.isBlank(emailDescription)) return incidentTime;
        String[] arr = emailDescription.split('\n'); 
            for(Integer i=0;i<arr.size();i++){
                String lcase = arr[i].substringBefore(':').toLowerCase();
                System.debug('array'+arr[i]);
                if(lcase.contains('incident time') || lcase.contains('incidenttime')){
                     incidentTime=arr[i].substringAfter(':').substringBefore('\n').trim();
                     System.debug('Incident Time' + incidentTime);
                    break;
                }
            }
        incidentTime = incidentTime.substring(0,incidentTime.lastIndexOf(':'))+incidentTime.substring(incidentTime.lastIndexOf(' '));
        String month=incidentTime.substring(0,incidentTime.indexOf('/'));
		String day = incidentTime.substring(incidentTime.indexOf('/')+1,incidentTime.lastIndexOf('/'));
        incidentTime=day+'/'+month+'/'+incidentTime.substring(incidentTime.lastIndexOf('/')+1).replaceFirst(' ',',');
        Datetime dt=DateTime.parse(incidentTime);
        System.debug('Incident Time is :'+incidentTime);
        System.debug('After Converting to DateTime : '+dt.format('yyyy-MM-dd HH:mm:ss'));
        return dt.format('yyyy-MM-dd HH:mm:ss');
    }

    public static void setLOB(Case thisCase)
    {
        if(thisCase.Origin=='EmailOHFC')
        {
            thisCase.Line_of_Business__c='OHFC';
            thisCase.Origin='Email';
        }else if(thisCase.Origin=='EmailSmallCell')
        {
            thisCase.Line_of_Business__c='Small Cell';
            thisCase.Origin='Email';
            thisCase.Case_Type__c='Issue';
        }else if(thisCase.Origin=='EmailUG')
        {
            thisCase.Line_of_Business__c='UG';
            thisCase.Origin='Email';
        }else if(thisCase.Origin=='EmailFTTH')
        {
            thisCase.Line_of_Business__c='FTTH';
            thisCase.Origin='Email';
        }
    }
    
    /*public static void setQueue(Case thisCase)
    {
        List<Group> queueObjs = [SELECT Id, Name, Email FROM Group WHERE Name = 'NOC' and Type='Queue']; //Id of the NOC queue defined in queues
        if(queueObjs.size()>0)
        {
            thisCase.OwnerId = queueObjs[0].Id; // dev NOC queue Id '00GC3000000m9aTMAQ';
            System.debug('queue id :' + thisCase.OwnerId);
        }
    }*/
    
    public static String getQueueId()
    {
        String QueueId = '';
        List<Group> queueObjs = [SELECT Id, Name, Email FROM Group WHERE Name = 'NOC' and Type='Queue']; //Id of the NOC queue defined in queues
        if(queueObjs.size()>0)
        {
            QueueId = queueObjs[0].Id;	// dev NOC queue Id '00GC3000000m9aTMAQ';
            System.debug('get queue id in Service Cloud Util Class called before insert of a case :' + QueueId);
        }
        return QueueId;
    }
    
    public static void setFTTHFields(Case thisCase)
    {
        System.debug('into setFTTHFields');
        String customerMessage = thisCase.Description;
        String incidentId = customerMessage.substringAfter('Incident:').substringBefore('Status:').trim();
        incidentId = incidentId.replaceAll(',','');
        String summary = customerMessage.substringAfter('Summary:').substringBefore('Actual Incident Time:').trim();
    	//thisCase.FTTHCaseType__c = 'PON';
        if(summary.contains('PON'))
            thisCase.FTTHCaseType__c = 'PON';
        if(summary.contains('INACT'))
			thisCase.FTTHCaseType__c = 'INACT';
        if(summary.contains('Mobility'))
            thisCase.FTTHCaseType__c = 'Mobility';
        String gpon = customerMessage.substringAfter('MSAN IP/Port Details:').substringBefore(', P_OBD:').trim();
        thisCase.GPON_Id__c = gpon; //comma separated GPON Ids from customer
        String FATs = customerMessage.substringAfter('S_OBD:').substringBefore(', BCL_ID:').trim();
        String FATNumbers = '';
        String[] FATArray = FATs.split(',');
        for (Integer i = 0; i<FATArray.size(); i++) //prepare a comma separated FAT list
        {
        	if(!FATArray[i].contains('Unknown') && !FATArray[i].contains('NULL')) //skip if value is unknown or null
            {
                if(FATArray[i].length()==11)
           			FATNumbers = FATNumbers + FATArray[i].substring(0,FATArray[i].length()-2) + ',';
                else
                    FATNumbers = FATNumbers + FATArray[i] + ',';
            }   
        }
        if(FATNumbers.length()>0)
        	FATNumbers = FATNumbers.substring(0,FATNumbers.length()-1); //to remove the last comma
        thisCase.FATNumber__c = FATNumbers; //comma separated FAT Numbers from customer
    }
	
    public static void createFTTHComponentsForCase(Case thisCase, String component)
    {
        System.debug('into create FTTH Component');
        if(component=='GPON')
            setGPONComponent(thisCase);
        else if(component=='FAT')
            setFATComponent(thisCase);
        
    }
    @TestVisible
    private static void setGPONComponent(Case thisCase)
    {
        String gpon = thisCase.GPON_Id__c;
        String[] gpons = gpon.split(',');
        for(Integer i=0;i<gpons.size();i++)
        {
			String gponNumber = gpons[i].trim();            
            List<GPON__c> gponMasterObj = [SELECT GPONId__c, InstallationAddress__c, FDCLocation__c, IsMobilityConnected__c, FieldEngineer__c, Circles__c, RSU__c, Latitude__c, Longitude__c FROM GPON__c where GPONId__c=:gponNumber];
            System.debug('gponsize'+gponMasterObj.size());
        	if(gponMasterObj.size()>0)
            {
                CaseFTTHComponent__c CFC = new CaseFTTHComponent__c();
                CFC.ComponentType__c='GPON';
                CFC.ComponentId__c = gponMasterObj[0].GPONId__c;
                CFC.Case__c=thisCase.Id;
                CFC.InstallationAddress__c = gponMasterObj[0].InstallationAddress__c;
                CFC.FDCLocation__c = gponMasterObj[0].FDCLocation__c;
                CFC.IsMobilityConnected__c = gponMasterObj[0].IsMobilityConnected__c;
                CFC.FieldEngineer__c = gponMasterObj[0].FieldEngineer__c;
                CFC.Circle__c = gponMasterObj[0].Circles__c;
                CFC.IsReported__c=true;
                CFC.Latitude__c= gponMasterObj[0].Latitude__c;
                CFC.Longitude__c= gponMasterObj[0].Longitude__c;
                insert CFC;
            }
        }
    }
    @TestVisible
    private static void setFATComponent(Case thisCase)
    {
        String FAT = thisCase.FATNumber__c;
        String[] FATs = FAT.split(',');
        for(Integer i=0;i<FATs.size();i++)
        {
            System.debug('service cloud FAT count : '+ FATs[i]);
            String fatNumber = FATs[i].trim();
            List<FAT__c> FATMasterObj = [SELECT GPONId__c, FATNumber__c, FATFullAddress__c, FATLocation__c, FDCLocation__c, IsMobilityConnected__c,Latitude__c,Longitude__c FROM FAT__c where FATNumber__c=:fatNumber];
        	if(FATMasterObj.size()>0)
            {
                System.debug('service cloud FAT count1 : '+ fatNumber + ' ' + FATMasterObj[0].FATNumber__c);
                CaseFTTHComponent__c CFC = new CaseFTTHComponent__c();
                CFC.ComponentType__c='FAT';
                CFC.Latitude__c= FATMasterObj[0].Latitude__c;
                CFC.Longitude__c= FATMasterObj[0].Longitude__c;
                CFC.FDCLocation__c=FATMasterObj[0].FDCLocation__c;
                CFC.ComponentId__c = FATMasterObj[0].FATNumber__c;
                CFC.Case__c=thisCase.Id;
                CFC.InstallationAddress__c= FATMasterObj[0].FATFullAddress__c;
                CFC.Location__c=FATMasterObj[0].FATLocation__c;
                CFC.IsMobilityConnected__c = FATMasterObj[0].IsMobilityConnected__c;
                if(FAT.contains(FATMasterObj[0].FATNumber__c)) //may not be required as we retrieve only the issues that are affected
                    CFC.IsReported__c=true;
                else
                    CFC.IsReported__c=false;
                insert CFC;
            }
        }
    }
    
    public static void checkForDuplicate(Case thisCase)
    {
        String LOB = thisCase.Line_of_Business__c;
        String CaseType = thisCase.Case_Type__c;
        List<Case> caseObj;
        if(LOB=='OHFC' && CaseType=='Issue')
       		caseObj = [SELECT Id,CaseNumber,Status,CreatedDate from Case where Circuit_ID__c=:thisCase.Circuit_ID__c and Line_of_Business__c=:LOB and (Status!='Resolved' and Status!='Closed' and Status!='Rework' and Status!='Duplicate') and Case_Type__c='Issue' order by CreatedDate desc];
        else if(LOB=='FTTH' && CaseType=='Issue')
            caseObj = [SELECT Id,CaseNumber,Status,CreatedDate from Case where GPON_Id__c=:thisCase.GPON_Id__c and Line_of_Business__c=:LOB and (Status!='Resolved' and Status!='Closed' and Status!='Rework' and Status!='Duplicate') and Case_Type__c='Issue' order by CreatedDate desc];
        else if(LOB=='UG' && CaseType=='Issue')
            System.debug('Route Name'+thisCase.RouteName__c);
            caseObj = [SELECT Id,CaseNumber,Status,CreatedDate from Case where ((Circuit_ID__c=:thisCase.Circuit_ID__c and Circuit_ID__c!=null) or (CustomerCircuitId__c=:thisCase.CustomerCircuitId__c and CustomerCircuitId__c!=null) or(RouteName__c=:thisCase.RouteName__c and RouteName__c!=null)) and Line_of_Business__c=:LOB and (Status!='Resolved' and Status!='Closed' and Status!='Rework' and Status!='Duplicate') and Case_Type__c='Issue' order by CreatedDate desc];
        
        if(CaseType=='Issue' && caseObj.size()>0) //duplicate open case
        {
            thisCase.Status='Duplicate';
            thisCase.OriginalCaseNumber__c = caseObj[0].CaseNumber;
            thisCase.ParentId=caseObj[0].Id;
        }
    }
    
    /*public static void getohfcAccountId(Case thisCase){
        String circuitId = thisCase.CircuitId__c;
        List<Circuit__c> circuitObj =[Select Primary_Customer_Name__c from Circuit__c where CircuitId__c =:circuitId];
        if(segmentObj.size()>0){
            thisCase.AccountId=segmentObj[0].Primary_Customer_Name__c;
            String accountId = thisCase.AccountId;
            List<Contact> contactObj=[Select Id from Contact where AccountId=:accountId and IsPrimaryContact__c=true];
            if(contactObj.size()>0)
            	thisCase.ContactId=contactObj[0].Id;
        }
    }*/
    
    public static void getftthAccountId(Case thisCase){
        String gponId = thisCase.GPON_Id__c;
        List<GPON__c> gponObj =[Select Primary_Customer_Name__c from GPON__c where GPONId__c =:gponId];
        if(gponObj.size()>0){
            thisCase.AccountId=gponObj[0].Primary_Customer_Name__c;
            String accountId = thisCase.AccountId;
        	List<Contact> contactObj=[Select Id from Contact where AccountId=:accountId and IsPrimaryContact__c=true];
        	if(contactObj.size()>0)
            	thisCase.ContactId=contactObj[0].Id;
            	System.debug(thisCase.ContactId);
        }
    }
}