force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User assigned to the Action.</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AssignedActions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Action.</description>
    <label>Description</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <defaultValue>Today()+ 3</defaultValue>
    <description>Due Date of the Action to be made.</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/DueDateFormula__c.field-meta.xml
<CustomField>
    <fullName>DueDateFormula__c</fullName>
    <description>Due Date of the Action to be made + Icon + Days left</description>
    <formula>IF(  
AND( ISPICKVAL( Status__c ,&quot;Open&quot;), DaysLeft__c &gt; 0) , Text(DueDate__c) &amp; &quot; ⚪️ &quot; &amp; Text(DaysLeft__c) &amp; &quot; Days Left&quot;  ,
IF(
AND( ISPICKVAL( Status__c ,&quot;Open&quot;), DaysLeft__c &lt;= 0) , Text(DueDate__c)&amp;&quot; 🟡 &quot; &amp; &quot; &quot; &amp; Text(ABS(DaysLeft__c)) &amp; &quot; Days Late&quot; , &quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <displayFormat>A-{000}</displayFormat>
    <externalId>true</externalId>
    <label>Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/IssueRisk__c.field-meta.xml
<CustomField>
    <fullName>IssueRisk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issue/Risk to which the Action is related.</description>
    <label>Issue / Risk</label>
    <referenceTo>IssueRisk__c</referenceTo>
    <relationshipLabel>Mitigation Actions</relationshipLabel>
    <relationshipName>RelatedActions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/OpenPoint__c.field-meta.xml
<CustomField>
    <fullName>OpenPoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Open Point</label>
    <referenceTo>OpenPoint__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FFCC66</color>
                <default>true</default>
                <label>🔄 Open</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#B6E32E</color>
                <label>✅ Closed</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>❎ Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IssueRisk__c/IssueRisk__c.object-meta.xml
<CustomObject>
    <label>Issue &amp; Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues &amp; Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IssueRisk__c/fields/Criticality__c.field-meta.xml
<CustomField>
    <fullName>Criticality__c</fullName>
    <label>Criticality</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
                <color>#000000</color>
                <label>⚫️ Critical</label>
            </value>
            <value>
                <fullName>High</fullName>
                <color>#CC0000</color>
                <default>true</default>
                <label>🔴 High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <color>#FFCC33</color>
                <label>🟠 Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <color>#FFFF66</color>
                <label>🟡 Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IssueRisk__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/IssueRisk__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <formula>CASE( Type__c, 
&quot;Risk&quot;, &quot;R-&quot; + Number__c , 
&quot;Issue&quot;, &quot;IS-&quot; + Number__c, 
&quot;IR-&quot; + Number__c) + &quot; - &quot; + TEXT(Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IssueRisk__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#CC0000</color>
                <default>true</default>
                <label>🔄 Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#006600</color>
                <label>✅ Closed</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#006600</color>
                <label>❎ Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpenPoint__c/OpenPoint__c.object-meta.xml
<CustomObject>
    <label>Open Point</label>
    <nameField>
        <label>Open Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpenPoint__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <displayFormat>OP-{000}</displayFormat>
    <externalId>true</externalId>
    <label>Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OpenPoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>🔄 Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>✅ Closed</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>❎ Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectReview__c/ProjectReview__c.object-meta.xml
<CustomObject>
    <label>Project Review</label>
    <nameField>
        <displayFormat>PR-{000}</displayFormat>
        <label>Project Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectReview__c/fields/LastProjectReviewDate__c.field-meta.xml
<CustomField>
    <fullName>LastProjectReviewDate__c</fullName>
    <label>Last Project Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProjectReview__c/fields/PMO__c.field-meta.xml
<CustomField>
    <fullName>PMO__c</fullName>
    <label>PMO</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ReviewGen.cls
public class ReviewGen {

    public static String generateRisksAndIssues(Date refDate) {
        
        Boolean isEmpty = true;
        
        Integer deltaDays = refDate.daysBetween(system.today());
		
        String review = '<strong>Issues & Risks</strong>';
     	
		String htmlResult = '<table>'
						+'<thead>'
        				+'<tr style="border : 1px solid black">'
            			+'<th>Id</th>'
            			+'<th>Title</th>'
            			+'<th>Criticality</th>' 
						+'<th></th>'             
        				+'</tr>'
    					+'</thead>'
    					+'<tbody>';
       
       String query =  'SELECT CreatedDate, Id, Id__c, toLabel(Status__c), Description__c, toLabel(Criticality__c), Name, Owner.Name '
					 + 'FROM IssueRisk__c WHERE (LastModifiedDate >= LAST_N_DAYS:' + deltaDays + ' OR Status__c = \'Open\')' 
					 + 'AND Status__c != \'Cancelled\''
					 + 'ORDER BY Criticality__c';
        
        for(IssueRisk__c issueOrRisk:Database.query(query)) {
         	
            isEmpty = false;
			String reviewStatus = '';
                                            
			if(issueOrRisk.CreatedDate > refDate) {
				reviewStatus = '✴️ New';
			}
			
			if(issueOrRisk.Status__c == '✅ Closed') {
				reviewStatus = '✅ Closed';
			}
                                            
			String intermediaryResult = '<tr style="border : 1px solid black">'
                +'<td>'+issueOrRisk.Id__c+'</td>'
                +'<td>'+issueOrRisk.Name+'</td>'
                +'<td>'+issueOrRisk.Criticality__c+'</td>'                    
                +'<td>'+reviewStatus+'</td>'                                        
                +'</tr>';     
                                            
			htmlResult += intermediaryResult;                                                                                    
        }
            
		htmlResult +=  '</tbody>' + '</table>';                
		
        if(!isEmpty) {
        	review += htmlResult;    
        }
        else {
            review = '';
        }
        
        return review;
    }
    
    public static String getDelta(Date refDate) {
        
        Integer theDay 	= refDate.Day();
        String theDayString = theDay < 10 ? '0' + theDay : '' + theDay;
        
        Integer theMonth = refDate.Month();
        String theMonthString = theMonth < 10 ? '0' + theMonth : '' + theMonth;
        
        String refDateString;  // theDayString + '/' + theMonthString;
        
		Integer diffDays = system.today().daysBetween(refDate);

        if(diffDays == -1) {
            refDateString = 'Yesterday';
        }
        else {
            refDateString = dayOfWeek(refDate);
        }
        
        return refDateString;
        
        // return refDateString;
    }
    
    public static String generateActions(Date refDate) {
        
        Integer deltaDays = refDate.daysBetween(system.today());
        deltaDays = deltaDays < 0 ? 0 : deltaDays;
        
        String refDateString = getDelta(refDate);
		
        Boolean isEmpty = true;
        String review = '<strong>Actions</strong>';
        
		String htmlResult = '<table>'
						+'<thead>'
        				+'<tr style="border : 1px solid black">'
            			+'<th>Id</th>'
            			+'<th>Title</th>' 
            			+'<th>Assigned To</th>'             
            			+'<th>Due Date</th>'  
						+'<th>Since ' +refDateString+'</th>'              
        				+'</tr>'
    					+'</thead>'
    					+'<tbody>';
        
        String query = 'SELECT Id, CreatedDate, Id__c, Status__c, DueDateFormula__c, Name, Owner.Name, DueDate__c, '
					   +' AssignedTo__r.Name '
            		   +'FROM Action__c WHERE Status__c = \'Open\' OR '
                       +'LastModifiedDate >= LAST_N_DAYS:' + deltaDays + ' ORDER BY DueDate__c ASC'; 
        
        system.debug('query : ' + query);
        
        for(Action__c action:Database.query(query)) {
            
			String reviewStatus = '';
            isEmpty = false;
            
           
            system.debug(action.CreatedDate > refDate);
           
			if(action.CreatedDate > refDate.addDays(1)) {
				reviewStatus = '✴️&nbsp;New';
			}
			
			if(action.Status__c == 'Completed') {
				reviewStatus = '✅&nbsp;Closed';
			}
			
            String dueDate = action.DueDate__c.Day()+'/'+action.DueDate__c.Month() + '/'+action.DueDate__c.Year();
            Integer diffDays = system.today().daysBetween(action.DueDate__c);
            String weekday = dayOfWeek(action.DueDate__c);
            
			if(diffDays == 0) {
                dueDate = '<strong>Today</strong>';
            }
            if(diffDays == 1) {
                dueDate = '<strong>Tomorrow</strong>';
            }
            else if(diffDays == -1) {
                dueDate = '<p style="color:#D72E2D;">️Yesterday</p>';
            }
            else if(diffDays < -1) {
                
                if(action.Status__c == 'Open') {
                    dueDate = '<p style="color:#D72E2D;">️' + dueDate + ' </p>';    
                }                     
            }
            else if(diffDays > 1 && diffDays <= 7) {
                dueDate = weekday;                
            }
            else if(diffDays > 7 ) {
                dueDate = weekday;                
            }            
            
			String intermediaryResult = '<tr style="border : 1px solid black">';
            
            if(action.Status__c == 'Completed') {
                intermediaryResult = '<tr style="border : 1px solid black; color : grey;">';
            }
            
            intermediaryResult += '<td>'+action.Id__c+'</td>'
                            	+'<td>'+action.Name+'</td>' 
                            	+'<td>'+action.AssignedTo__r.Name+'</td>'                 
                				+'<td>'+dueDate+'</td>'
                				+'<td>'+reviewStatus+'</td>'                
                            	+'</tr>';    
            
			htmlResult += intermediaryResult;                                   
        }
            
		htmlResult +=  '</tbody>' + '</table>';                
		
    	if(!isEmpty) {
        	review += htmlResult;    
        }
        else {
            review = '';
        }
                
        return review;
    }
    
    public static String generateOpenPoints(Date refDate) {
        
        Boolean isEmpty = true;
        Integer deltaDays = refDate.daysBetween(system.today());
        
        String refDateString = getDelta(refDate);
        
		String review = '<strong>Open Points</strong>';
     
		String htmlResult = '<table>'
						+'<thead>'
        				+'<tr style="border : 1px solid black">'
            			+'<th>Id</th>'
            			+'<th>Description</th>'
						+'<th>Since ' +refDateString+'</th>'                       
        				+'</tr>'
    					+'</thead>'
    					+'<tbody>';
        
        String query = 'SELECT Id, Id__c, CreatedDate, Status__c, Name, Description__c '
            		 + 'FROM OpenPoint__c WHERE Status__c = \'Open\' OR LastModifiedDate >= LAST_N_DAYS:' 
            		 + deltaDays + ' ORDER BY CreatedDate DESC';
        
        for(OpenPoint__c op:Database.query(query)) {
         
            String reviewStatus = '';
            isEmpty = false;
            
			if(op.CreatedDate > refDate.addDays(1)) {
				reviewStatus = '✴️&nbsp;New';
			}
			
			if(op.Status__c == 'Completed') {
				reviewStatus = '✅&nbsp;Closed';
			}            
            
			String intermediaryResult = '<tr style="border : 1px solid black">'
                            +'<td>'+op.Id__c+'</td>'
                            +'<td>'+op.Name+'</td>'                  
							+'<td>' + reviewStatus + '</td>'                                  
                            +'</tr>';     
			htmlResult += intermediaryResult;                                   
        }
            
		htmlResult +=  '</tbody>' + '</table>';                

    	if(!isEmpty) {
        	review += htmlResult;    
        }
        else {
            review = '';
        }
        
        return review;
    }    

    public static void generateProjectReview(Id projectReviewId) {
		
        ProjectReview__c pr = [SELECT Id, PMO__c, LastProjectReviewDate__c FROM ProjectReview__c WHERE ID = :projectReviewId];
        
        String actionReview = generateActions(pr.LastProjectReviewDate__c); 
        String opReview = generateOpenPoints(pr.LastProjectReviewDate__c); 
		String riskAndIssues = generateRisksAndIssues(pr.LastProjectReviewDate__c);
        
        pr.PMO__c = riskAndIssues + '<br/><br/>' + actionReview + '<br/><br/>' + opReview ;
        update pr;
    }
    
    public static String dayOfWeek(Date aDate) {
        
        String dayOfWeek;
        Integer weekDayNumber = Math.mod(Date.newInstance(1900, 1, 7).daysBetween(aDate),7);
        
        switch on weekDayNumber {
            when 0 { dayOfWeek = 'Sunday'; }            	
            when 1 { dayOfWeek = 'Monday'; }
            when 2 { dayOfWeek = 'Tuesday'; }
            when 3 { dayOfWeek = 'Wednesday'; }     
            when 4 { dayOfWeek = 'Thursday'; }                 
            when 5 { dayOfWeek = 'Friday'; }                      
            when 6 { dayOfWeek = 'Saturday'; }                                  
            when else { }
        }
        
        return dayOfWeek;
    }    
    
}